SET
Table: _migrations_applied | RLS: false | Policies: 0
Table: account_types | RLS: false | Policies: 0
Table: activity_logs | RLS: true | Policies: 2
Table: admin_messages | RLS: false | Policies: 0
Table: bank_accounts | RLS: false | Policies: 4
Table: banks | RLS: false | Policies: 0
Table: business_visual_settings | RLS: true | Policies: 4
Table: carousel_slides | RLS: true | Policies: 2
Table: cart_items | RLS: false | Policies: 0
Table: category_discounts | RLS: false | Policies: 1
Table: category_rules | RLS: false | Policies: 0
Table: combo_items | RLS: false | Policies: 0
Table: combo_products | RLS: true | Policies: 2
Table: cuban_municipalities | RLS: false | Policies: 0
Table: currencies | RLS: false | Policies: 0
Table: exchange_rates | RLS: false | Policies: 0
Table: inventory | RLS: false | Policies: 0
Table: inventory_movements | RLS: false | Policies: 1
Table: manager_assignments | RLS: false | Policies: 0
Table: notification_logs | RLS: false | Policies: 0
Table: notification_settings | RLS: true | Policies: 4
Table: offer_items | RLS: false | Policies: 0
Table: offer_usage | RLS: true | Policies: 3
Table: offers | RLS: false | Policies: 0
Table: operational_costs | RLS: false | Policies: 0
Table: order_items | RLS: true | Policies: 2
Table: order_status_history | RLS: false | Policies: 0
Table: orders | RLS: true | Policies: 3
Table: product_categories | RLS: true | Policies: 2
Table: products | RLS: true | Policies: 4
Table: publications | RLS: true | Policies: 5
Table: recipient_addresses | RLS: false | Policies: 0
Table: recipient_bank_accounts | RLS: false | Policies: 4
Table: recipients | RLS: false | Policies: 0
Table: remittance_bank_transfers | RLS: false | Policies: 3
Table: remittance_services | RLS: false | Policies: 0
Table: remittance_status_history | RLS: false | Policies: 0
Table: remittance_types | RLS: true | Policies: 2
Table: remittances | RLS: true | Policies: 8
Table: shipping_zones | RLS: false | Policies: 0
Table: shopping_carts | RLS: false | Policies: 0
Table: site_visits | RLS: false | Policies: 0
Table: system_config | RLS: true | Policies: 3
Table: system_messages | RLS: false | Policies: 0
Table: testimonials | RLS: true | Policies: 3
Table: user_alerts | RLS: true | Policies: 4
Table: user_categories | RLS: false | Policies: 0
Table: user_category_history | RLS: false | Policies: 0
Table: user_profiles | RLS: true | Policies: 5
Table: videos | RLS: false | Policies: 0
Table: zelle_accounts | RLS: false | Policies: 0
Table: zelle_payment_stats | RLS: false | Policies: 0
Table: zelle_transaction_history | RLS: false | Policies: 0
