import React, { createContext, useContext, useState } from 'react';

const LanguageContext = createContext();

const translations = {
  es: {
    common: {
      success: 'Éxito',
      error: 'Error',
      cancel: 'Cancelar',
      loading: 'Cargando...',
      search: 'Buscar',
      save: 'Guardar',
      delete: 'Eliminar',
      edit: 'Editar',
      close: 'Cerrar',
      confirm: 'Confirmar',
      actions: 'Acciones',
      status: 'Estado',
      all: 'Todos',
      type: 'Tipo',
      number: 'Número',
      date: 'Fecha',
      createdAt: 'Fecha de Creación'
    },
    nav: {
      home: 'Inicio',
      products: 'Productos',
      remittances: 'Remesas',
      admin: 'Administración',
      dashboard: 'Panel de Control',
      settings: 'Configuración',
      cart: 'Carrito',
      userPanel: 'Mi Panel',
      userManagement: 'Gestión de Usuarios'
    },
    home: {
      hero: {
        cta: {
          products: 'Ver Productos',
        }
      },
      features: {
        title: 'Funcionalidades Principales',
        subtitle: 'Todo lo que necesitas para hacer crecer tu negocio digital',
        products: { title: 'Venta de Productos', description: 'Plataforma completa para vendedores independientes con cálculo automático de precios' },
        remittances: { title: 'Remesas a Cuba', description: 'Envía dinero a Cuba desde USA y España de forma rápida y segura' },
        analytics: { title: 'Panel de Ganancias', description: 'Visualiza tus ganancias diarias y mensuales en tiempo real' },
        vendors: { title: 'Gestión de Vendedores', description: 'Herramientas completas para que vendedores independientes gestionen su inventario' }
      },
      testimonials: {
        title: 'Lo que dicen nuestros clientes',
        subtitle: 'Experiencias reales de usuarios satisfechos con nuestra plataforma.'
      }
    },
    products: {
      title: 'Catálogo de Productos',
      subtitle: 'Descubre productos y combos para enviar a Cuba con precios competitivos',
      searchPlaceholder: 'Buscar productos...',
      categories: { all: 'Todas las Categorías' },
      exchangeRate: 'Tasa de Cambio Actual',
      addToCart: 'Agregar al Carrito',
      vendor: 'Vendedor',
      noProducts: 'No se encontraron productos',
      noProductsDesc: 'Intenta con otros términos de búsqueda o categorías',
      addProduct: 'Agregar Producto',
      addedToCart: 'Producto agregado',
      addedToCartDesc: 'se agregó al carrito exitosamente',
      detail: {
        previous: 'Anterior',
        next: 'Siguiente',
        backToProducts: '← Volver a Productos',
        backToCombos: '← Volver a Combos',
        continueToProducts: 'Continuar a Productos →',
        continueToCombos: 'Continuar a Combos →',
        price: 'Precio',
        basePrice: 'Precio Base',
        category: 'Categoría',
        description: 'Descripción',
        stock: 'Stock Disponible',
        expiryDate: 'Fecha de Vencimiento',
        currency: 'Moneda',
        includedProducts: 'Productos Incluidos',
        profitMargin: 'Margen de Ganancia',
        comboDetails: 'Detalles del Combo',
        productDetails: 'Detalles del Producto',
        inStock: 'En Stock',
        outOfStock: 'Agotado',
        units: 'unidades'
      }
    },
    remittances: {
      title: 'Remesas a Cuba',
      subtitle: 'Envía dinero a Cuba desde USA y España de forma rápida y segura',
      calculator: 'Calculadora de Remesas',
      amount: 'Cantidad a Enviar (USD)',
      country: 'País de Destino',
      selectCountry: 'Seleccionar país...',
      currentRate: 'Tasa Actual',
      popular: 'Popular',
      rate: 'Tasa',
      fee: 'Comisión',
      time: 'Tiempo',
      youReceive: 'Recibes',
      send: 'Enviar Remesa',
      sendNew: 'Nueva Remesa',
      myRemittances: 'Mis Remesas',
      howItWorks: '¿Cómo Funciona?',
      step1: { title: 'Selecciona el País', description: 'Elige el país de destino y la cantidad a enviar' },
      step2: { title: 'Confirma los Datos', description: 'Verifica la información del destinatario' },
      step3: { title: 'Recibe Confirmación', description: 'El dinero llega en el tiempo estimado' },
      recipient: {
        title: 'Datos del Destinatario',
        deliveryMethod: 'Método de Entrega',
        cash: 'Efectivo',
        transfer: 'Transferencia',
        currency: 'Moneda',
        fullName: 'Nombre Completo',
        phone: 'Teléfono',
        city: 'Ciudad',
        address: 'Dirección',
        idNumber: 'Carnet de Identidad',
        notes: 'Notas adicionales',
        bankName: 'Nombre del Banco',
        accountNumber: 'Número de Cuenta',
        confirm: 'Confirmar y Enviar'
      },
      status: {
        paymentPending: 'Pendiente de Pago',
        paymentProofUploaded: 'Comprobante Enviado',
        paymentValidated: 'Pago Validado',
        paymentRejected: 'Pago Rechazado',
        processing: 'En Proceso',
        delivered: 'Entregado',
        completed: 'Completado',
        cancelled: 'Cancelado'
      },
      alert: {
        pending: 'Pendiente de validación',
        delivered: 'Entregada',
        overdue: 'Entrega vencida',
        hoursLeft: 'Quedan {hours} horas',
        daysLeft: 'Quedan {days} días'
      },
      admin: {
        title: 'Gestión de Remesas',
        types: 'Tipos de Remesas',
        newType: 'Nuevo Tipo',
        editType: 'Editar Tipo',
        newRemittanceType: 'Nuevo Tipo de Remesa',
        editRemittanceType: 'Editar Tipo de Remesa',
        typeName: 'Nombre del Tipo',
        typeNamePlaceholder: 'Ej: Dólares a CUP (Efectivo)',
        originCurrency: 'Moneda de Origen',
        deliveryCurrency: 'Moneda de Entrega',
        exchangeRate: 'Tasa de Cambio',
        commissionPercent: 'Comisión (%)',
        commissionFixed: 'Comisión Fija',
        minAmount: 'Monto Mínimo',
        maxAmount: 'Monto Máximo',
        maxDeliveryDays: 'Días Máximos de Entrega',
        warningDays: 'Días para Alerta',
        active: 'Activo',
        inactive: 'Inactivo',
        description: 'Descripción',
        descriptionPlaceholder: 'Descripción del tipo de remesa...',
        icon: 'Ícono',
        displayOrder: 'Orden de Visualización',
        deliveryMethod: 'Método de Entrega',
        save: 'Guardar',
        cancel: 'Cancelar',
        edit: 'Editar',
        delete: 'Eliminar',
        activate: 'Activar',
        deactivate: 'Desactivar',
        confirmDelete: '¿Está seguro de eliminar este tipo de remesa?',
        deleteWarning: 'Esta acción no se puede deshacer. Las remesas existentes no se verán afectadas.',
        requiredFields: 'Por favor complete todos los campos requeridos',
        typeCreated: 'Tipo de remesa creado',
        typeUpdated: 'Tipo de remesa actualizado',
        typeDeleted: 'Tipo de remesa eliminado',
        typeActivated: 'Tipo activado',
        typeDeactivated: 'Tipo desactivado',
        pendingValidation: 'Pendientes de Validación',
        inProgress: 'En Progreso',
        urgent: 'Urgentes',
        total: 'Total',
        validate: 'Validar',
        reject: 'Rechazar',
        process: 'Procesar',
        confirmDelivery: 'Confirmar Entrega',
        complete: 'Completar',
        viewDetails: 'Ver Detalles',
        rejectReason: 'Razón del rechazo',
        rejectReasonPlaceholder: 'Ej: Comprobante ilegible, datos incorrectos...',
        validationNotes: 'Notas de validación',
        validationNotesPlaceholder: 'Añadir notas sobre la validación...',
        deliveryNotes: 'Notas de entrega',
        deliveryNotesPlaceholder: 'Detalles de la entrega...',
        confirmValidateMessage: '¿Confirma que el pago de {amount} {currency} es válido?',
        confirmRejectMessage: '¿Por qué se rechaza el pago de {number}?',
        confirmProcessMessage: 'Iniciar procesamiento de remesa {number}?',
        confirmDeliveryMessage: 'Confirmar entrega de {amount} {currency} a {recipient}?',
        confirmCompleteMessage: '¿Marcar remesa {number} como completada?',
        noTypes: 'No hay tipos de remesas configurados',
        loadingTypes: 'Cargando tipos de remesas...',
        searchPlaceholder: 'Buscar por número, destinatario o teléfono...',
        allStatuses: 'Todos los estados',
        paymentValidated: 'Pago validado correctamente',
        paymentRejected: 'Pago rechazado',
        processingStarted: 'Procesamiento iniciado',
        deliveryConfirmed: 'Entrega confirmada',
        remittanceCompleted: 'Remesa completada'
      },
      user: {
        trackYourRemittances: 'Consulte el estado de sus envíos de dinero',
        noRemittances: 'No tiene remesas registradas',
        noRemittancesDesc: 'Envíe su primera remesa de forma rápida y segura',
        remittanceNumber: 'Número de Remesa',
        amountSent: 'Enviado',
        toDeliver: 'A Entregar',
        method: 'Método',
        uploadProof: 'Subir Comprobante',
        reUploadProof: 'Reenviar Comprobante',
        cancel: 'Cancelar',
        cancelRemittance: 'Cancelar Remesa',
        cancelReason: 'Razón (opcional)',
        paymentProof: 'Comprobante de pago',
        paymentReference: 'Referencia de pago',
        uploadFile: 'Subir archivo',
        additionalNotes: 'Notas adicionales',
        viewProof: 'Ver Comprobante'
      },
      wizard: {
        step1Title: 'Tipo y Monto de Remesa',
        step2Title: 'Datos del Destinatario',
        step3Title: 'Confirmar Remesa',
        step4Title: 'Comprobante de Pago',
        selectType: 'Seleccione el tipo de remesa',
        amountToSend: 'Monto a enviar',
        limits: 'Límites',
        calculationSummary: 'Resumen del Cálculo',
        youSend: 'Monto a enviar',
        commission: 'Comisión',
        recipientReceives: 'Destinatario recibirá',
        confirmAndCreate: 'Confirmar Remesa',
        remittanceCreated: 'Remesa Creada',
        uploadLater: 'Subir Después',
        sendProof: 'Enviar Comprobante',
        importantNote: 'Importante',
        proofNote: 'Su remesa será procesada una vez validemos el comprobante de pago. Recibirá una notificación cuando esto ocurra.'
      }
    },
    vendor: {
      title: 'Gestión de la Plataforma',
      subtitle: 'Gestiona productos, categorías, combos y más.',
      tabs: {
        inventory: 'Inventario',
        categories: 'Categorías',
        combos: 'Combos',
        management: 'Gestión'
      },
      actions: {
        addProduct: 'Agregar Producto',
        createCombo: 'Crear Combo',
      },
      addProduct: {
        title: 'Agregar Nuevo Producto',
        editTitle: 'Editar Producto',
        cancel: 'Cancelar',
        name: 'Nombre del Producto',
        namePlaceholder: 'Ej: iPhone 15 Pro Max',
        description: 'Descripción',
        descriptionPlaceholder: 'Describe las características principales...',
        category: 'Categoría',
        basePrice: 'Precio Base',
        currency: 'Moneda',
        image: 'Imagen del Producto',
        upload: 'Subir archivo',
        finalPrice: 'Precio Final',
        save: 'Guardar Producto'
      },
      inventory: {
        product: 'Producto',
        stock: 'Existencias',
        price: 'Precio Final',
        expiryDate: 'Fecha de Caducidad'
      },
      categories: {
        manage: 'Gestionar Categorías',
        new: 'Nueva categoría',
        name_es: 'Nombre (ES)',
        name_en: 'Nombre (EN)',
        id: 'ID'
      },
      combos: {
        title: 'Gestión de Combos',
        new: 'Crear Nuevo Combo',
        edit: 'Editar Combo',
        name: 'Nombre del Combo',
        profitMargin: 'Margen de Ganancia (%)',
        shipping: 'Envío',
        free: 'Gratis',
        discount: 'Descuento (%)',
        paid: 'Pagado',
        shippingCost: 'Costo de Envío',
        products: 'Productos en el Combo',
        addProduct: 'Agregar Producto',
        basePrice: 'Precio Base Total',
        finalPrice: 'Precio Final',
        coverImage: 'Imagen de Portada',
        save: 'Guardar Combo'
      },
      management: {
        title: 'Gestión General',
        payments: 'Gestión de Pagos',
        testimonials: 'Gestión de Testimonios',
        users: 'Gestión de Usuarios',
        show: 'Mostrar',
        hide: 'Ocultar',
        activate: 'Activar',
        deactivate: 'Desactivar',
        delete: 'Eliminar'
      },
      validation: { error: 'Error de Validación', fillFields: 'Por favor completa todos los campos requeridos' },
      productAdded: 'Producto agregado exitosamente',
      productUpdated: 'Producto actualizado exitosamente',
      categoryAdded: 'Categoría agregada',
      categoryRemoved: 'Categoría eliminada',
      comboAdded: 'Combo creado exitosamente',
      comboUpdated: 'Combo actualizado exitosamente'
    },
    dashboard: {
      title: 'Panel de Control',
      subtitle: 'Visualización completa de ganancias y métricas del negocio',
      privateAccess: 'Acceso Privado',
      adminOnly: 'Esta sección es solo para administradores.',
      refresh: 'Actualizar',
      stats: {
        dailyRevenue: 'Ingresos Diarios',
        monthlyRevenue: 'Ingresos Mensuales',
        dailyProfit: 'Ganancia Diaria',
        monthlyProfit: 'Ganancia Mensual',
        totalProducts: 'Total de Productos',
        totalCombos: 'Total de Combos',
        pendingOrders: 'Pedidos Pendientes',
        completedOrders: 'Pedidos Completados',
        totalUsers: 'Total de Usuarios',
        activeProducts: 'Productos Activos',
        siteVisits: 'Visitas al Sitio'
      },
      profitBreakdown: 'Desglose de Ganancias',
      dailyBreakdown: 'Desglose Diario',
      monthlyBreakdown: 'Desglose Mensual',
      grossRevenue: 'Ingresos Brutos',
      costs: 'Costos',
      netProfit: 'Ganancia Neta',
      profitMargin: 'Margen de Ganancia',
      orderSummary: 'Resumen de Pedidos',
      pending: 'Pendientes',
      completed: 'Completados',
      overviewTab: 'Resumen General',
      ordersTab: 'Historial de Órdenes',
      orderStatus: {
        paymentPending: 'Pago Pendiente',
        paymentValidated: 'Pago Validado',
        processing: 'En Procesamiento',
        shipped: 'Enviado',
        delivered: 'Entregado',
        cancelled: 'Cancelado',
        totalActive: 'Total Activas'
      },
      analyticsTitle: 'Análisis y Estadísticas',
      selectCurrency: 'Seleccionar Moneda',
      expirationWarning: {
        title: 'Alerta de Caducidad',
        description: 'Hay {count} producto(s) próximos a caducar en los siguientes 30 días.'
      },
      visits: {
        title: 'Visitas al Sitio',
        weekly: 'Semanal',
        monthly: 'Mensual',
        yearly: 'Anual',
        total: 'Total',
        thisWeek: 'Esta Semana',
        thisMonth: 'Este Mes',
        thisYear: 'Este Año',
        allTime: 'Histórico'
      }
    },
    settings: {
      title: 'Ajustes Generales',
      subtitle: 'Gestiona la configuración clave de tu plataforma.',
      financial: {
        title: 'Ajustes Financieros',
        usdToLocal: 'USD a Moneda Nacional',
        productProfit: 'Ganancia Productos (%)',
        comboProfit: 'Ganancia Combos (%)',
        remittanceProfit: 'Ganancia Remesas (%)',
        save: 'Guardar Ajustes',
        currencies: 'Gestión de Monedas',
        addCurrency: 'Agregar Moneda',
        code: 'Código (ej: USD, EUR, CUP)',
        nameES: 'Nombre (Español)',
        nameEN: 'Nombre (Inglés)',
        rate: 'Tasa vs USD',
        symbol: 'Símbolo',
        active: 'Activa',
        updateCurrency: 'Actualizar Moneda',
        currencyCreated: 'Moneda creada',
        currencyUpdated: 'Moneda actualizada',
        currencyDeleted: 'Moneda eliminada'
      },
      zelle: {
        title: 'Cuentas Zelle',
        add: 'Agregar Cuenta Zelle',
        email: 'Email',
        name: 'Nombre',
        assignTo: 'Asignar a',
        products: 'Venta de Productos',
        remittances: 'Remesas',
        active: 'Activa'
      },
      visual: {
        title: 'Ajustes Visuales',
        logo: 'Logo del Sitio',
        favicon: 'Favicon',
        slides: 'Diapositivas de Portada',
        addSlide: 'Agregar Diapositiva',
        image: 'Imagen (URL o Archivo)',
        imageType: 'Tipo de Imagen',
        url: 'URL',
        upload: 'Subir',
        mainText: 'Texto Principal',
        secondaryText: 'Texto Secundario',
        text_es: 'Texto (ES)',
        text_en: 'Texto (EN)',
        linkUrl: 'Enlace (URL)',
        order: 'Orden',
        active: 'Activa',
        save: 'Guardar Ajustes'
      },
      notifications: {
        title: 'Ajustes de Notificación',
        whatsapp: 'Número de WhatsApp para Notificaciones',
        adminEmail: 'Email de Administración para Notificaciones',
        save: 'Guardar Ajustes'
      },
      saveSuccess: 'Ajustes guardados exitosamente'
    },
    cart: {
      title: 'Tu Carrito de Compras',
      empty: 'Tu carrito está vacío.',
      browse: 'Explorar productos',
      summary: 'Resumen del Pedido',
      subtotal: 'Subtotal',
      shipping: 'Envío',
      free: 'Gratis',
      total: 'Total',
      checkout: 'Proceder al Pago',
      payment: {
        title: 'Realizar Pago',
        instructionsTitle: 'Instrucciones de Pago',
        instructions: "Copia el ID de la compra y pégalo en la descripción de la transferencia Zelle. Envía el comprobante a info@papuenvios.com o súbelo directamente aquí. El pago estará sujeto a validación.",
        accountInfo: 'Datos de la Cuenta Zelle',
        purchaseId: 'ID de la Compra',
        copy: 'Copiado',
        amount: 'Monto a Pagar',
        uploadProof: 'Subir Comprobante de Pago',
        confirm: 'Confirmar Pago',
        recipientTitle: 'Datos de Entrega/Destinatario'
      }
    },
    auth: {
      login: 'Iniciar Sesión',
      loginTitle: 'Bienvenido de Nuevo',
      loginSubtitle: 'Inicia sesión para acceder a tu cuenta.',
      email: 'Correo Electrónico',
      password: 'Contraseña',
      loginWithGoogle: 'Iniciar Sesión con Google',
      or: 'O',
      loginSuccess: '¡Inicio de sesión exitoso!',
      loginError: 'Credenciales inválidas. Por favor, intenta de nuevo.',
      logoutSuccess: 'Sesión cerrada exitosamente.',
      loginRequired: 'Inicio de Sesión Requerido',
      loginToCheckout: 'Por favor, inicia sesión para continuar con el pago.',
    },
    userPanel: {
      title: 'Mi Panel de Usuario',
      welcome: 'Bienvenido, {name}',
      myOrders: 'Mis Pedidos',
      noOrders: 'Aún no tienes pedidos.',
      status: {
        pending: 'Pendiente',
        validated: 'Validado',
        rejected: 'Rechazado'
      }
    },
    adminOrders: {
      title: 'Historial de Órdenes',
      subtitle: 'Gestión completa de todas las órdenes del sistema',
      stats: {
        total: 'Total',
        pending: 'Pendientes',
        validated: 'Validadas',
        rejected: 'Rechazadas',
        completed: 'Completadas',
        revenue: 'Ingresos'
      },
      filters: {
        title: 'Filtros de Búsqueda',
        clear: 'Limpiar Filtros',
        search: 'Buscar',
        searchPlaceholder: 'Orden, usuario, email o producto...',
        status: 'Estado de la Orden',
        allStatuses: 'Todos los Estados',
        orderType: 'Tipo de Orden',
        allTypes: 'Todos',
        startDate: 'Fecha Inicio',
        endDate: 'Fecha Fin',
        apply: 'Aplicar Filtros'
      },
      table: {
        order: 'Orden',
        user: 'Usuario',
        date: 'Fecha',
        type: 'Tipo',
        items: 'Items',
        total: 'Total',
        paymentStatus: {
          label: 'Estado Pago',
          pending: 'Pago Pendiente',
          validated: 'Pago Validado (Listo para Procesar)',
          rejected: 'Pago Rechazado'
        },
        orderStatus: {
          label: 'Estado Orden',
          pending: 'Pendiente',
          processing: 'En Procesamiento',
          shipped: 'Enviado',
          delivered: 'Entregado',
          completed: 'Completado',
          cancelled: 'Cancelado'
        },
        actions: 'Acciones'
      },
      types: {
        products: 'Productos',
        remittance: 'Remesa',
        mixed: 'Mixto'
      },
      actions: {
        view: 'Ver',
        start: 'Iniciar',
        ship: 'Enviar',
        proof: 'Evidencia',
        complete: 'Completar',
        cancel: 'Cancelar',
        processing: 'Procesando...',
        loading: 'Cargando...',
        completing: 'Completando...'
      },
      messages: {
        noOrders: 'No se encontraron órdenes',
        retry: 'Reintentar',
        confirmStart: '¿Iniciar procesamiento de la orden {orderNumber}?',
        confirmComplete: '¿Marcar la orden {orderNumber} como completada?',
        confirmCancel: '¿Está seguro de cancelar esta orden? Esta acción liberará el inventario reservado.',
        enterTracking: 'Ingrese número de tracking (opcional) para la orden {orderNumber}:',
        enterCancelReason: 'Ingrese razón de cancelación para la orden {orderNumber}:',
        cancelReasonRequired: 'Debe especificar una razón para cancelar',
        startSuccess: 'Orden movida a estado "En Procesamiento"',
        shipSuccess: 'Orden marcada como "Enviada"',
        deliverSuccess: 'Evidencia de entrega subida exitosamente. Orden marcada como "Entregada"',
        completeSuccess: 'Orden completada exitosamente',
        cancelSuccess: 'Orden cancelada exitosamente',
        error: 'Error',
        selectImage: 'Seleccione una imagen de evidencia',
        invalidImage: 'Por favor seleccione una imagen válida',
        imageTooLarge: 'El archivo es muy grande. Máximo 5MB'
      },
      deliveryModal: {
        title: 'Subir Evidencia de Entrega',
        orderLabel: 'Orden:',
        customerLabel: 'Cliente:',
        selectPhoto: 'Seleccionar Foto de Evidencia',
        clickToUpload: 'Click para subir',
        dragHere: 'o arrastra aquí',
        fileTypes: 'PNG, JPG, JPEG (MAX. 5MB)',
        imageLoaded: 'Imagen cargada. Haga click en "Subir Evidencia" para confirmar.',
        note: 'Nota:',
        noteText: 'Al subir la evidencia, la orden se marcará automáticamente como "Entregada". El cliente podrá ver la foto de evidencia.',
        cancel: 'Cancelar',
        submit: 'Subir Evidencia',
        uploading: 'Subiendo...'
      },
      days: {
        singular: 'día',
        plural: 'días'
      },
      modals: {
        confirm: 'Confirmar',
        cancel: 'Cancelar',
        submit: 'Enviar',
        startTitle: 'Iniciar Procesamiento',
        completeTitle: 'Completar Orden',
        cancelTitle: 'Cancelar Orden',
        trackingTitle: 'Número de Tracking',
        cancelReasonTitle: 'Razón de Cancelación'
      }
    },
    users: {
      management: 'Gestión de Usuarios',
      managementDescription: 'Administra roles y permisos de usuarios de la plataforma',
      fetchError: 'Error al cargar usuarios',
      roleUpdated: 'Rol actualizado',
      roleUpdatedSuccess: 'El rol del usuario se actualizó correctamente',
      roleUpdateError: 'Error al actualizar rol',
      userEnabled: 'Usuario habilitado',
      userDisabled: 'Usuario deshabilitado',
      statusUpdateSuccess: 'El estado del usuario se actualizó correctamente',
      statusUpdateError: 'Error al actualizar estado',
      cannotModifySuperAdmin: 'No se puede modificar al super administrador',
      superAdmin: 'Super Admin',
      noUsers: 'No hay usuarios',
      enable: 'Habilitar',
      disable: 'Deshabilitar',
      delete: 'Eliminar',
      deleteUser: 'Eliminar usuario',
      enableUser: 'Activar usuario',
      disableUser: 'Desactivar usuario',
      userDeleted: 'Usuario eliminado',
      userDeletedSuccess: 'El usuario ha sido eliminado exitosamente.',
      deleteError: 'Error al eliminar',
      confirmDelete: '¿Estás seguro de que deseas eliminar a {email}? Esta acción no se puede deshacer.',
      protected: 'Protegido',
      refresh: 'Actualizar',
      loadingUsers: 'Cargando usuarios...',
      noUsersFound: 'No se encontraron usuarios',
      total: 'Total',
      rolesPermissions: {
        title: 'Roles y Permisos',
        userDesc: 'Acceso básico al sistema',
        adminDesc: 'Gestión de productos, combos e inventario',
        superAdminDesc: 'Acceso total + gestión de usuarios'
      },
      securityNote: {
        title: 'Nota de seguridad',
        superAdminProtected: 'Los Super Admins están protegidos y no pueden ser editados ni eliminados',
        onlySuperAdminManage: 'Solo Super Admins pueden gestionar roles y eliminar usuarios',
        deletionPermanent: 'La eliminación de usuarios es permanente y no se puede deshacer'
      },
      roles: {
        user: 'Usuario',
        admin: 'Administrador',
        super_admin: 'Super Administrador'
      },
      table: {
        email: 'Correo Electrónico',
        name: 'Nombre',
        role: 'Rol',
        status: 'Estado',
        actions: 'Acciones',
        active: 'Activo',
        inactive: 'Inactivo',
        createdAt: 'Fecha de Registro'
      }
    }
  },
  en: {
    common: {
      success: 'Success',
      error: 'Error',
      cancel: 'Cancel',
      loading: 'Loading...',
      search: 'Search',
      save: 'Save',
      delete: 'Delete',
      edit: 'Edit',
      close: 'Close',
      confirm: 'Confirm',
      actions: 'Actions',
      status: 'Status',
      all: 'All',
      type: 'Type',
      number: 'Number',
      date: 'Date',
      createdAt: 'Created At'
    },
    nav: {
      home: 'Home',
      products: 'Products',
      remittances: 'Remittances',
      admin: 'Administration',
      dashboard: 'Control Panel',
      settings: 'Settings',
      cart: 'Cart',
      userPanel: 'My Panel',
      userManagement: 'User Management'
    },
    home: {
      hero: {
        cta: { products: 'View Products' }
      },
      features: {
        title: 'Key Features',
        subtitle: 'Everything you need to grow your digital business',
        products: { title: 'Product Sales', description: 'Complete platform for independent vendors with automatic price calculation' },
        remittances: { title: 'Remittances to Cuba', description: 'Send money to Cuba from USA and Spain quickly and securely' },
        analytics: { title: 'Profit Dashboard', description: 'View your daily and monthly profits in real-time' },
        vendors: { title: 'Vendor Management', description: 'Complete tools for independent vendors to manage their inventory' }
      },
      testimonials: {
        title: 'What our customers say',
        subtitle: 'Real experiences from users satisfied with our platform.'
      }
    },
    products: {
      title: 'Product Catalog',
      subtitle: 'Discover exclusive products and combos to send to Cuba with competitive prices',
      searchPlaceholder: 'Search products...',
      categories: { all: 'All Categories' },
      exchangeRate: 'Current Exchange Rate',
      addToCart: 'Add to Cart',
      vendor: 'Vendor',
      noProducts: 'No products found',
      noProductsDesc: 'Try different search terms or categories',
      addProduct: 'Add Product',
      addedToCart: 'Product added',
      addedToCartDesc: 'was successfully added to cart',
      detail: {
        previous: 'Previous',
        next: 'Next',
        backToProducts: '← Back to Products',
        backToCombos: '← Back to Combos',
        continueToProducts: 'Continue to Products →',
        continueToCombos: 'Continue to Combos →',
        price: 'Price',
        basePrice: 'Base Price',
        category: 'Category',
        description: 'Description',
        stock: 'Available Stock',
        expiryDate: 'Expiry Date',
        currency: 'Currency',
        includedProducts: 'Included Products',
        profitMargin: 'Profit Margin',
        comboDetails: 'Combo Details',
        productDetails: 'Product Details',
        inStock: 'In Stock',
        outOfStock: 'Out of Stock',
        units: 'units'
      }
    },
    remittances: {
      title: 'Remittances to Cuba',
      subtitle: 'Send money to Cuba from USA and Spain quickly and securely',
      calculator: 'Remittance Calculator',
      amount: 'Amount to Send (USD)',
      country: 'Destination Country',
      selectCountry: 'Select country...',
      currentRate: 'Current Rate',
      popular: 'Popular',
      rate: 'Rate',
      fee: 'Fee',
      time: 'Time',
      youReceive: 'You Receive',
      send: 'Send Remittance',
      sendNew: 'New Remittance',
      myRemittances: 'My Remittances',
      howItWorks: 'How It Works?',
      step1: { title: 'Select Country', description: 'Choose destination country and amount to send' },
      step2: { title: 'Confirm Details', description: 'Verify recipient information' },
      step3: { title: 'Receive Confirmation', description: 'Money arrives within estimated time' },
      recipient: {
        title: 'Recipient Details',
        deliveryMethod: 'Delivery Method',
        cash: 'Cash',
        transfer: 'Transfer',
        currency: 'Currency',
        fullName: 'Full Name',
        phone: 'Phone',
        city: 'City',
        address: 'Address',
        idNumber: 'ID Number',
        notes: 'Additional notes',
        bankName: 'Bank Name',
        accountNumber: 'Account Number',
        confirm: 'Confirm & Send'
      },
      status: {
        paymentPending: 'Payment Pending',
        paymentProofUploaded: 'Proof Sent',
        paymentValidated: 'Payment Validated',
        paymentRejected: 'Payment Rejected',
        processing: 'Processing',
        delivered: 'Delivered',
        completed: 'Completed',
        cancelled: 'Cancelled'
      },
      alert: {
        pending: 'Pending validation',
        delivered: 'Delivered',
        overdue: 'Delivery overdue',
        hoursLeft: '{hours} hours left',
        daysLeft: '{days} days left'
      },
      admin: {
        title: 'Remittance Management',
        types: 'Remittance Types',
        newType: 'New Type',
        editType: 'Edit Type',
        newRemittanceType: 'New Remittance Type',
        editRemittanceType: 'Edit Remittance Type',
        typeName: 'Type Name',
        typeNamePlaceholder: 'Ex: Dollars to CUP (Cash)',
        originCurrency: 'Origin Currency',
        deliveryCurrency: 'Delivery Currency',
        exchangeRate: 'Exchange Rate',
        commissionPercent: 'Commission (%)',
        commissionFixed: 'Fixed Commission',
        minAmount: 'Minimum Amount',
        maxAmount: 'Maximum Amount',
        maxDeliveryDays: 'Max Delivery Days',
        warningDays: 'Warning Days',
        active: 'Active',
        inactive: 'Inactive',
        description: 'Description',
        descriptionPlaceholder: 'Remittance type description...',
        icon: 'Icon',
        displayOrder: 'Display Order',
        deliveryMethod: 'Delivery Method',
        save: 'Save',
        cancel: 'Cancel',
        edit: 'Edit',
        delete: 'Delete',
        activate: 'Activate',
        deactivate: 'Deactivate',
        confirmDelete: 'Are you sure you want to delete this remittance type?',
        deleteWarning: 'This action cannot be undone. Existing remittances will not be affected.',
        requiredFields: 'Please complete all required fields',
        typeCreated: 'Remittance type created',
        typeUpdated: 'Remittance type updated',
        typeDeleted: 'Remittance type deleted',
        typeActivated: 'Type activated',
        typeDeactivated: 'Type deactivated',
        pendingValidation: 'Pending Validation',
        inProgress: 'In Progress',
        urgent: 'Urgent',
        total: 'Total',
        validate: 'Validate',
        reject: 'Reject',
        process: 'Process',
        confirmDelivery: 'Confirm Delivery',
        complete: 'Complete',
        viewDetails: 'View Details',
        rejectReason: 'Rejection reason',
        rejectReasonPlaceholder: 'Ex: Receipt illegible, incorrect data...',
        validationNotes: 'Validation notes',
        validationNotesPlaceholder: 'Add notes about validation...',
        deliveryNotes: 'Delivery notes',
        deliveryNotesPlaceholder: 'Delivery details...',
        confirmValidateMessage: 'Confirm that the payment of {amount} {currency} is valid?',
        confirmRejectMessage: 'Why is the payment for {number} being rejected?',
        confirmProcessMessage: 'Start processing remittance {number}?',
        confirmDeliveryMessage: 'Confirm delivery of {amount} {currency} to {recipient}?',
        confirmCompleteMessage: 'Mark remittance {number} as completed?',
        noTypes: 'No remittance types configured',
        loadingTypes: 'Loading remittance types...',
        searchPlaceholder: 'Search by number, recipient or phone...',
        allStatuses: 'All statuses',
        paymentValidated: 'Payment validated successfully',
        paymentRejected: 'Payment rejected',
        processingStarted: 'Processing started',
        deliveryConfirmed: 'Delivery confirmed',
        remittanceCompleted: 'Remittance completed'
      },
      user: {
        trackYourRemittances: 'Track your money transfers status',
        noRemittances: 'No remittances registered',
        noRemittancesDesc: 'Send your first remittance quickly and securely',
        remittanceNumber: 'Remittance Number',
        amountSent: 'Sent',
        toDeliver: 'To Deliver',
        method: 'Method',
        uploadProof: 'Upload Proof',
        reUploadProof: 'Re-upload Proof',
        cancel: 'Cancel',
        cancelRemittance: 'Cancel Remittance',
        cancelReason: 'Reason (optional)',
        paymentProof: 'Payment proof',
        paymentReference: 'Payment reference',
        uploadFile: 'Upload file',
        additionalNotes: 'Additional notes',
        viewProof: 'View Proof'
      },
      wizard: {
        step1Title: 'Type and Amount',
        step2Title: 'Recipient Details',
        step3Title: 'Confirm Remittance',
        step4Title: 'Payment Proof',
        selectType: 'Select remittance type',
        amountToSend: 'Amount to send',
        limits: 'Limits',
        calculationSummary: 'Calculation Summary',
        youSend: 'Amount to send',
        commission: 'Commission',
        recipientReceives: 'Recipient will receive',
        confirmAndCreate: 'Confirm Remittance',
        remittanceCreated: 'Remittance Created',
        uploadLater: 'Upload Later',
        sendProof: 'Send Proof',
        importantNote: 'Important',
        proofNote: 'Your remittance will be processed once we validate the payment proof. You will receive a notification when this happens.'
      }
    },
    vendor: {
      title: 'Platform Management',
      subtitle: 'Manage products, categories, combos, and more.',
      tabs: {
        inventory: 'Inventory',
        categories: 'Categories',
        combos: 'Combos',
        management: 'Management'
      },
      actions: {
        addProduct: 'Add Product',
        createCombo: 'Create Combo',
      },
      addProduct: {
        title: 'Add New Product',
        editTitle: 'Edit Product',
        cancel: 'Cancel',
        name: 'Product Name',
        namePlaceholder: 'Ex: iPhone 15 Pro Max',
        description: 'Description',
        descriptionPlaceholder: 'Describe main features...',
        category: 'Category',
        basePrice: 'Base Price',
        currency: 'Currency',
        image: 'Product Image',
        upload: 'Upload file',
        finalPrice: 'Final Price',
        save: 'Save Product'
      },
      inventory: {
        product: 'Product',
        stock: 'Stock',
        price: 'Final Price',
        expiryDate: 'Expiry Date'
      },
      categories: {
        manage: 'Manage Categories',
        new: 'New category',
        name_es: 'Name (ES)',
        name_en: 'Name (EN)',
        id: 'ID'
      },
      combos: {
        title: 'Combo Management',
        new: 'Create New Combo',
        edit: 'Edit Combo',
        name: 'Combo Name',
        profitMargin: 'Profit Margin (%)',
        shipping: 'Shipping',
        free: 'Free',
        discount: 'Discount (%)',
        paid: 'Paid',
        shippingCost: 'Shipping Cost',
        products: 'Products in Combo',
        addProduct: 'Add Product',
        basePrice: 'Total Base Price',
        finalPrice: 'Final Price',
        coverImage: 'Cover Image',
        save: 'Save Combo'
      },
      management: {
        title: 'General Management',
        payments: 'Payment Management',
        testimonials: 'Testimonial Management',
        users: 'User Management',
        show: 'Show',
        hide: 'Hide',
        activate: 'Activate',
        deactivate: 'Deactivate',
        delete: 'Delete'
      },
      validation: { error: 'Validation Error', fillFields: 'Please fill all required fields' },
      productAdded: 'Product added successfully',
      productUpdated: 'Product updated successfully',
      categoryAdded: 'Category added',
      categoryRemoved: 'Category removed',
      comboAdded: 'Combo created successfully',
      comboUpdated: 'Combo updated successfully'
    },
    dashboard: {
      title: 'Control Panel',
      subtitle: 'Complete visualization of profits and business metrics',
      privateAccess: 'Private Access',
      adminOnly: 'This section is for administrators only.',
      refresh: 'Refresh',
      stats: {
        dailyRevenue: 'Daily Revenue',
        monthlyRevenue: 'Monthly Revenue',
        dailyProfit: 'Daily Profit',
        monthlyProfit: 'Monthly Profit',
        totalProducts: 'Total Products',
        totalCombos: 'Total Combos',
        pendingOrders: 'Pending Orders',
        completedOrders: 'Completed Orders',
        totalUsers: 'Total Users',
        activeProducts: 'Active Products',
        siteVisits: 'Site Visits'
      },
      profitBreakdown: 'Profit Breakdown',
      dailyBreakdown: 'Daily Breakdown',
      monthlyBreakdown: 'Monthly Breakdown',
      grossRevenue: 'Gross Revenue',
      costs: 'Costs',
      netProfit: 'Net Profit',
      profitMargin: 'Profit Margin',
      orderSummary: 'Order Summary',
      pending: 'Pending',
      completed: 'Completed',
      overviewTab: 'Overview',
      ordersTab: 'Order History',
      orderStatus: {
        paymentPending: 'Payment Pending',
        paymentValidated: 'Payment Validated',
        processing: 'Processing',
        shipped: 'Shipped',
        delivered: 'Delivered',
        cancelled: 'Cancelled',
        totalActive: 'Total Active'
      },
      analyticsTitle: 'Analytics & Statistics',
      selectCurrency: 'Select Currency',
      expirationWarning: {
        title: 'Expiration Alert',
        description: 'There are {count} product(s) nearing expiration in the next 30 days.'
      },
      visits: {
        title: 'Site Visits',
        weekly: 'Weekly',
        monthly: 'Monthly',
        yearly: 'Yearly',
        total: 'Total',
        thisWeek: 'This Week',
        thisMonth: 'This Month',
        thisYear: 'This Year',
        allTime: 'All Time'
      }
    },
    settings: {
      title: 'General Settings',
      subtitle: 'Manage the key settings of your platform.',
      financial: {
        title: 'Financial Settings',
        usdToLocal: 'USD to Local Currency',
        productProfit: 'Product Profit (%)',
        comboProfit: 'Combo Profit (%)',
        remittanceProfit: 'Remittance Profit (%)',
        save: 'Save Settings',
        currencies: 'Currency Management',
        addCurrency: 'Add Currency',
        code: 'Code (e.g: USD, EUR, CUP)',
        nameES: 'Name (Spanish)',
        nameEN: 'Name (English)',
        rate: 'Rate vs USD',
        symbol: 'Symbol',
        active: 'Active',
        updateCurrency: 'Update Currency',
        currencyCreated: 'Currency created',
        currencyUpdated: 'Currency updated',
        currencyDeleted: 'Currency deleted'
      },
      zelle: {
        title: 'Zelle Accounts',
        add: 'Add Zelle Account',
        email: 'Email',
        name: 'Name',
        assignTo: 'Assign to',
        products: 'Product Sales',
        remittances: 'Remittances',
        active: 'Active'
      },
      visual: {
        title: 'Visual Settings',
        logo: 'Site Logo',
        favicon: 'Favicon',
        slides: 'Homepage Slides',
        addSlide: 'Add Slide',
        image: 'Image (URL or File)',
        imageType: 'Image Type',
        url: 'URL',
        upload: 'Upload',
        mainText: 'Main Text',
        secondaryText: 'Secondary Text',
        text_es: 'Text (ES)',
        text_en: 'Text (EN)',
        active: 'Active',
        save: 'Save Settings'
      },
      notifications: {
        title: 'Notification Settings',
        whatsapp: 'WhatsApp Number for Notifications',
        adminEmail: 'Admin Email for Notifications',
        save: 'Save Settings'
      },
      saveSuccess: 'Settings saved successfully'
    },
    cart: {
      title: 'Your Shopping Cart',
      empty: 'Your cart is empty.',
      browse: 'Browse products',
      summary: 'Order Summary',
      subtotal: 'Subtotal',
      shipping: 'Shipping',
      free: 'Free',
      total: 'Total',
      checkout: 'Proceed to Checkout',
      payment: {
        title: 'Make Payment',
        instructionsTitle: 'Payment Instructions',
        instructions: "Copy the purchase ID and paste it into the Zelle transfer description. Send the receipt to info@papuenvios.com or upload it directly here. The payment will be subject to validation.",
        accountInfo: 'Zelle Account Details',
        purchaseId: 'Purchase ID',
        copy: 'Copied',
        amount: 'Amount to Pay',
        uploadProof: 'Upload Payment Proof',
        confirm: 'Confirm Payment',
        recipientTitle: 'Delivery/Recipient Details'
      }
    },
    auth: {
      login: 'Login',
      loginTitle: 'Welcome Back',
      loginSubtitle: 'Log in to access your account.',
      email: 'Email',
      password: 'Password',
      loginWithGoogle: 'Login with Google',
      or: 'Or',
      loginSuccess: 'Login successful!',
      loginError: 'Invalid credentials. Please try again.',
      logoutSuccess: 'Logged out successfully.',
      loginRequired: 'Login Required',
      loginToCheckout: 'Please log in to continue to checkout.',
    },
    userPanel: {
      title: 'My User Panel',
      welcome: 'Welcome, {name}',
      myOrders: 'My Orders',
      noOrders: 'You have no orders yet.',
      status: {
        pending: 'Pending',
        validated: 'Validated',
        rejected: 'Rejected'
      }
    },
    adminOrders: {
      title: 'Order History',
      subtitle: 'Complete management of all system orders',
      stats: {
        total: 'Total',
        pending: 'Pending',
        validated: 'Validated',
        rejected: 'Rejected',
        completed: 'Completed',
        revenue: 'Revenue'
      },
      filters: {
        title: 'Search Filters',
        clear: 'Clear Filters',
        search: 'Search',
        searchPlaceholder: 'Order, user, email or product...',
        status: 'Order Status',
        allStatuses: 'All Statuses',
        orderType: 'Order Type',
        allTypes: 'All',
        startDate: 'Start Date',
        endDate: 'End Date',
        apply: 'Apply Filters'
      },
      table: {
        order: 'Order',
        user: 'User',
        date: 'Date',
        type: 'Type',
        items: 'Items',
        total: 'Total',
        paymentStatus: {
          label: 'Payment Status',
          pending: 'Payment Pending',
          validated: 'Payment Validated (Ready to Process)',
          rejected: 'Payment Rejected'
        },
        orderStatus: {
          label: 'Order Status',
          pending: 'Pending',
          processing: 'Processing',
          shipped: 'Shipped',
          delivered: 'Delivered',
          completed: 'Completed',
          cancelled: 'Cancelled'
        },
        actions: 'Actions'
      },
      types: {
        products: 'Products',
        remittance: 'Remittance',
        mixed: 'Mixed'
      },
      actions: {
        view: 'View',
        start: 'Start',
        ship: 'Ship',
        proof: 'Proof',
        complete: 'Complete',
        cancel: 'Cancel',
        processing: 'Processing...',
        loading: 'Loading...',
        completing: 'Completing...'
      },
      messages: {
        noOrders: 'No orders found',
        retry: 'Retry',
        confirmStart: 'Start processing order {orderNumber}?',
        confirmComplete: 'Mark order {orderNumber} as completed?',
        confirmCancel: 'Are you sure you want to cancel this order? This action will release reserved inventory.',
        enterTracking: 'Enter tracking number (optional) for order {orderNumber}:',
        enterCancelReason: 'Enter cancellation reason for order {orderNumber}:',
        cancelReasonRequired: 'You must specify a reason for cancellation',
        startSuccess: 'Order moved to "Processing" status',
        shipSuccess: 'Order marked as "Shipped"',
        deliverSuccess: 'Delivery proof uploaded successfully. Order marked as "Delivered"',
        completeSuccess: 'Order completed successfully',
        cancelSuccess: 'Order cancelled successfully',
        error: 'Error',
        selectImage: 'Select proof image',
        invalidImage: 'Please select a valid image',
        imageTooLarge: 'File is too large. Maximum 5MB'
      },
      deliveryModal: {
        title: 'Upload Delivery Proof',
        orderLabel: 'Order:',
        customerLabel: 'Customer:',
        selectPhoto: 'Select Proof Photo',
        clickToUpload: 'Click to upload',
        dragHere: 'or drag here',
        fileTypes: 'PNG, JPG, JPEG (MAX. 5MB)',
        imageLoaded: 'Image loaded. Click "Upload Proof" to confirm.',
        note: 'Note:',
        noteText: 'When uploading proof, the order will be automatically marked as "Delivered". The customer will be able to see the proof photo.',
        cancel: 'Cancel',
        submit: 'Upload Proof',
        uploading: 'Uploading...'
      },
      days: {
        singular: 'day',
        plural: 'days'
      },
      modals: {
        confirm: 'Confirm',
        cancel: 'Cancel',
        submit: 'Submit',
        startTitle: 'Start Processing',
        completeTitle: 'Complete Order',
        cancelTitle: 'Cancel Order',
        trackingTitle: 'Tracking Number',
        cancelReasonTitle: 'Cancellation Reason'
      }
    },
    users: {
      management: 'User Management',
      managementDescription: 'Manage platform user roles and permissions',
      fetchError: 'Error loading users',
      roleUpdated: 'Role updated',
      roleUpdatedSuccess: 'User role was updated successfully',
      roleUpdateError: 'Error updating role',
      userEnabled: 'User enabled',
      userDisabled: 'User disabled',
      statusUpdateSuccess: 'User status was updated successfully',
      statusUpdateError: 'Error updating status',
      cannotModifySuperAdmin: 'Cannot modify super administrator',
      superAdmin: 'Super Admin',
      noUsers: 'No users',
      enable: 'Enable',
      disable: 'Disable',
      delete: 'Delete',
      deleteUser: 'Delete user',
      enableUser: 'Enable user',
      disableUser: 'Disable user',
      userDeleted: 'User deleted',
      userDeletedSuccess: 'User has been deleted successfully.',
      deleteError: 'Error deleting',
      confirmDelete: 'Are you sure you want to delete {email}? This action cannot be undone.',
      protected: 'Protected',
      refresh: 'Refresh',
      loadingUsers: 'Loading users...',
      noUsersFound: 'No users found',
      total: 'Total',
      rolesPermissions: {
        title: 'Roles & Permissions',
        userDesc: 'Basic system access',
        adminDesc: 'Product, combo and inventory management',
        superAdminDesc: 'Full access + user management'
      },
      securityNote: {
        title: 'Security Note',
        superAdminProtected: 'Super Admins are protected and cannot be edited or deleted',
        onlySuperAdminManage: 'Only Super Admins can manage roles and delete users',
        deletionPermanent: 'User deletion is permanent and cannot be undone'
      },
      roles: {
        user: 'User',
        admin: 'Administrator',
        super_admin: 'Super Administrator'
      },
      table: {
        email: 'Email',
        name: 'Name',
        role: 'Role',
        status: 'Status',
        actions: 'Actions',
        active: 'Active',
        inactive: 'Inactive',
        createdAt: 'Registration Date'
      }
    }
  }
};

export const LanguageProvider = ({ children }) => {
  const [language, setLanguage] = useState('es');

  const t = (key, params = {}) => {
    const keys = key.split('.');
    let value = translations[language];
    
    for (const k of keys) {
      value = value?.[k];
    }
    
    if (typeof value === 'string') {
      return Object.entries(params).reduce(
        (acc, [paramKey, paramValue]) => acc.replace(`{${paramKey}}`, paramValue),
        value
      );
    }
    
    return value || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};